# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp

compiler:
  - gcc
  - clang

branches:
  only:
    - master

script:
  - make test DEBUG_FLAGS="-W -Wall -Wextra -Werror -Wno-long-long -pedantic -fstrict-aliasing -g -O1 -DLIBDIVIDE_ASSERTIONS_ON=1 -msse2 -DLIBDIVIDE_USE_SSE2=1"
